cni-version = "1.0.0"
name = "dbnet"
type = "portmap"

[[runtime-config.port-mappings]]
host-port = 8080
container-port = 80
protocol = "tcp"

[[prev-result.ips]]
address = "10.1.0.5/16"
gateway = "10.1.0.1"
interface = 2

[[prev-result.routes]]
dst = "0.0.0.0/0"

[[prev-result.interfaces]]
name = "cni0"
mac = "00:11:22:33:44:55"

[[prev-result.interfaces]]
name = "veth3243"
mac = "55:44:33:22:11:11"

[[prev-result.interfaces]]
name = "eth0"
mac = "00:11:22:33:44:66"
sandbox = "/var/run/netns/blue"

[prev-result.dns]
name-servers = [ "10.1.0.1" ]
