version = 2

root = "/var/lib/containerd"
state = "/run/containerd"
oom-score = 0
imports = [ "/etc/containerd/runtime_*.toml", "./debug.toml" ]

[grpc]
address = "/run/containerd/containerd.sock"
uid = 0
gid = 0

[debug]
address = "/run/containerd/debug.sock"
uid = 0
gid = 0
level = "Info"

[metrics]
address = ""
grpc-histogram = false

[cgroup]
path = ""

[plugins]
[plugins."io.containerd.monitor.v1.cgroups"]
no-prometheus = false

[plugins."io.containerd.service.v1.diff-service"]
default = [ "Walking" ]

[plugins."io.containerd.gc.v1.scheduler"]
pause-threshold = 0.02
deletion-threshold = 0
mutation-threshold = 100
schedule-delay = 0
startup-delay = "100ms"

[plugins."io.containerd.runtime.v2.task"]
platforms = [ "linux/amd64" ]
sched-core = true

[plugins."io.containerd.service.v1.tasks-service"]
blockio-config-file = ""
rdt-config-file = ""
