api-version = "cert-manager.io/v1"
kind = "Certificate"

[metadata]
name = "ca"
namespace = "default"

[spec]
is-ca = true
secret-name = "ca"
common-name = "ca"

[spec.private-key]
algorithm = "ECDSA"
size = 256

[spec.issuer-ref]
name = "self-signed"
kind = "Issuer"
