api-version = "gateway.networking.k8s.io/v1beta1"
kind = "HTTPRoute"

[metadata]
name = "http-app-1"

[[spec.parentRefs]]
name = "my-gateway"
namespace = "default"

[[spec.rules]]
[[spec.rules.matches]]
[spec.rules.matches.path]
type = "PathPrefix"
value = "/details"

[[spec.rules.backend-refs]]
name = "details"
port = 9080

[[spec.rules]]
[[spec.rules.matches]]
method = "GET"

[[spec.rules.matches.headers]]
type = "Exact"
name = "magic"
value = "foo"

[[spec.rules.matches.query-params]]
type = "Exact"
name = "great"
value = "example"

[spec.rules.matches.path]
type = "PathPrefix"
value = "/"

[[spec.rules.backend-refs]]
name = "productpage"
port = 9080
