api-version = "gateway.networking.k8s.io/v1alpha2"
kind = "Gateway"

[metadata]
name = "example"

[metadata.annotations]
"cert-manager.io/issuer" = "foo"

[spec]
gateway-class-name = "foo"

[[spec.listeners]]
name = "http"
hostname = "example.com"
port = 443
protocol = "HTTPS"

[spec.listeners.allowed-routes.namespaces]
from = "All"

[spec.listeners.tls]
mode = "Terminate"

[[spec.listeners.tls.certificate-refs]]
name = "example-com-tls"
