api-version = "cilium.io/v2"
kind = "CiliumNetworkPolicy"

[metadata]
name = "icmp-rule"

[spec.endpoint-selector.match-labels]
app = "myService"

[[spec.egress]]
[[spec.egress.icmps]]
[[spec.egress.icmps.fields]]
type = 8
family = "IPv4"

[[spec.egress.icmps.fields]]
type = 128
family = "IPv6"
